### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by mattkol** [prasannavl/WinApi#18]
Hi,

Please I need your help.

Is RealtimeEventLoop  expected to consume more CPU usage than EventLoop?

Please see this [issue from Chromely](https://github.com/mattkol/Chromely/issues/14) and my [RealtimeEventLoop ](https://github.com/mattkol/Chromely/blob/master/src/Chromely.CefGlue.Winapi/HostEventLoop.cs).

I will revert back to EventLoop but just want be sure that this is expected and not something that I am doing wrong.

**Comment by prasannavl** [comment]
Yes. `RealtimeEventLoop` will use 100% of the CPU. It's meant for games and the likes that wants complete control over the event loop. Please look at https://github.com/prasannavl/WinApi/blob/master/WinApi/Windows/EventLoop.cs#L62 vs https://github.com/prasannavl/WinApi/blob/master/WinApi/Windows/EventLoop.cs#L45 for the differences. It use the `PeekMessage` on a loop instead of `GetMessage` intentionally. 

Note: For Chromely, you want `EventLoop`, not `RealtimeEventLoop`. If you use RealtimeEventLoop, it's your responsibility to let the thread sleep until there's a new message on the Win32 message queue.

**Comment by prasannavl** [comment]
PS: I also looked at your `HostEventLoop`. You've basically re-implemented your own loop. ~~All `EventLoop` variations in this library are just helpers to accomplish the same. So, you don't even need to derive it from `EventLoopCore`.~~ (Sorry, what you've done is correct. This is exactly what `EventLoopCore` was meant for. It was my bad, I mistook using `EventLoopCore` for `EventLoop`.)  

That aside, you're still looping through the message queue with PeekMessage constantly. When you use `PeekMessage` that way, it's your responsibility to wait, or it will use 100% of the CPU. 

So, I suggest your issue is due to the incorrect use of `GetMessage` vs `PeekMessage`. Please have a look at MSDN for them. Long story short - you want to be using GetMessage instead of PeekMessage. Or if you *really really* have to peek, then peek first and get next -- so you're not in a constantly running loop.

**Comment by mattkol** [comment]
Thanks a lot!

**Comment by prasannavl** [comment]
Happy to help. But use caution if you pick the Peek + Get route, as it only works for one-shot. You're mostly better off with just using GetMessage, swallowing the message, and dispatching it on your own again if you want to do it for all messages - though that introduces more state. 

I just looked at your event loop again, is there a reason you're using PeekMessage? Can you just not GetMessage instead? (Or does Chrome DoMessageLoopWork call GetMessage on it's own? -- in which case, I'd probably just try to handle quit inside the chrome loop - That'd probably be simpler).

**Comment by mattkol** [comment]
I was trying to deal with Idle process and stepped on my foot in the process.
I will revert back to GetMessage and leave Idle part to user customization.

Thank you.
