### ISSUE TITLE
InitMouseInput Signature

### ISSUE THREAD

**Issue by vflame** [prasannavl/WinApi#9]
The InitMouseInput signature only accepts unit for 'data'. It should accept uint to allow for the mouse scroll down event.

**Comment by prasannavl** [comment]
@vflame 

Thanks for bringing this up :)

The `mouseData` field is variable. It contains mouse scroll event only when `dwFlags` contains `MOUSEEVENTF_WHEEL`. That's why isn't not in the structure. 

Ref: https://msdn.microsoft.com/en-us/library/windows/desktop/ms646273(v=vs.85).aspx

However, what I'd like to do is like the `KeyboardInput` structure, it should include helper methods that extract it.  Could you try it? A PR would be awesome :)

**Comment by vflame** [comment]
I'm not sure if this is 'kosher' or not but I just changed the signature from uint to int and scrolling up and down is working as expected. 

I'm not following what you mean by using a helper method extract the variable. I'm not very familiar with winapi.

**Comment by prasannavl** [comment]
@vflame  - I'm guessing you're facing problems because you're somehow losing the sign bit during the int-uint conversion. You probably might want to look at the application code. 

> I'm not following what you mean by using a helper method extract the variable. I'm not very familiar with winapi.

Essentially, another overloaded `InitMouseInput` with the proper scroll values, which automatically set's the `dwFlags` to 1 as well. That should be the correct approach. 

PS: For a quick solution though, the MouseInput structure is transparent, so you can just create it manually and do whatever you want, as a workaround. :)

**Comment by vflame** [comment]
I also found casting the int to uint using unchecked (permitting the overflow) works as well without any changes to the existing source. Thanks for the library.
